name: Xây Dựng Generic System Image

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://dllb2.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2MTQwODg0ODIiLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6IjcyN2M4NmExMzViMjY1ZTViZWI3NDE2MDljYzkxMWRkYzRhYmNhYzE2MmQ4NGU5ZThiNzFjNzAzY2M1NTJhZWQ0ODgyNmZkNDA2Zjk4OTczNzQyMDNjYWE4NzQ0Y2NmYTQxNWNiMTk0NWY4ZjJhZGUzYzZmYmU4ZTIyOTIxN2QxIiwidCI6MTYxNjUxNzE0Mywic3RmcCI6IjM5YjhiMzFmYTM1MzIxZGE0NzgxNTA4MzQ5MTYwZDJmIiwic3RpcCI6IjIwMDE6ZWUwOjRmY2Y6NTFhMDo2NTliOjk5NjE6N2E4MjozODRiIn0.gX_pisVX7ZNk3wT98gP5XVg266dl-LhfuZCc0PN2AUk/Corvus_v14.5-Mutate-lavender-Gapps-22022021-OFFICIAL-2013.zip
  ROM_NAME: Generic
  BUILD_AB: true
  BUILD_Aonly: true
  ROM_AONLY: ROM_A.7z
  ROM_AB: ROM_test_AB.7z

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Kiểm Tra Trích Xuất
         uses: actions/checkout@master
       
       - name: Dọn Dẹp Đầy Đủ
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Thiết Lập Môi Trường 
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip
       
       - name: Lấy Nguồn 
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Thiết lập các yêu cầu 
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Tải Xuống ROM - Khởi Tạo Aonly GSI
         if: env.BUILD_AONLY == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -a $ROM_URL $ROM_NAME
       
       - name: 7z Aonly GSI
         if: env.BUILD_AONLY == 'true'
         run: 7za a -t7z -r $ROM_AONLY ErfanGSIs/output/*
       
       - name: Upload Aonly
         if: env.BUILD_AONLY == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit $ROM_AONLY
           
       - name: Dọn Dẹp Đầu Ra
         if: env.BUILD_AB == 'true'
         run: sudo rm -rf ErfanGSIs/output/*
         
       - name: Tải Xuống ROM - Khởi Tạo AB GSI
         if: env.BUILD_AB == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -b $ROM_URL $ROM_NAME

       - name: 7z AB GSI
         if: env.BUILD_AB == 'true'
         run: 7za a -t7z -r $ROM_AB ErfanGSIs/output/*

       - name: Upload AB 
         if: env.BUILD_AB == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit $ROM_AB
              
           
